### ISSUE TITLE
folders for all drives until z:

### ISSUE THREAD

**Issue by ghost** [shanecoughlan/OpenGEM#4]
When manually copying opengem to c: in FreeDOS 1.2 it works, but produces shortcuts to all drives up to and including z:, although the machines only drive is c:

I can't find a way to get rid of the useless shortcuts, and unfortunately I can't find out the reason they get created at all. The options-menu for adding a drive is greyed out -- perhaps it's got something to do with it?

**Comment by ghost** [comment]
Seems to have been a failure of the freedos installer, it produced an extended partition after C: and populates is with seemingly as much logical partitions as it can. These are detected by opengem.

Fix with fdisk from a live-Linux, now opengem works as expected.

**Comment by shanecoughlan** [comment]
Glad it worked out! Sorry to hear the FreeDOS installer is causing problems though :(
